{% set version = "2.0.4" %}

package:
  name: bob.db.atnt
  version: {{ version }}

source:
  fn: bob.db.atnt-{{ version }}.zip
  md5: 65e060d39e7d9b3d1200974968648d32
  url: https://pypi.python.org/packages/source/b/bob.db.atnt/bob.db.atnt-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - bob.db.base
    - bob.db.verification.utils

  run:
    - python
    - bob.db.base
    - bob.db.verification.utils

test:
  commands:
    - nosetests -sv bob.db.atnt

  imports:
    - bob
    - bob.db
    - bob.db.atnt

  requires:
    - nose

about:
  home: http://github.com/bioidiap/bob.db.atnt
  license: GNU General Public License v3 (GPLv3)
  summary: ATNT/ORL Database Access API for Bob

extra:
  recipe-maintainers:
    - 183amir
