travis:
  secure:
    BINSTAR_TOKEN: gnPwSUWYtYR5EZUYzrW045RFqqdc+AnfEmmlTQJ3j6w6Od5u72PuIpfs5GJ1m9k8W9cI/W8Nj7mavnHIa6j07EQ7ATuc7bHZIPKO+Abb6/naE85z/k8kCs8qSNcjiSxDMJScCnVxjBIVMy8/CaHDCwU59Zl7nnxSXji9MKFsb3JeFf9T4r0A67+l0D9+TeVeJyYah8pKfwe3GStl3D71sgZafrR3+jIGKqpArdvWfL0J+Em4xm099KhH/QdUmLY9PntQytvnAunXqN5j5/P0cwfsEooNX0ie8xhWplEWqmBGAcoo3uZeOKelQ9AwR3TTAnJhw2pezttHlRzfgLEb4fxprw3kJvkRiu6ovSLS6DqdJbsOR13mWwhtljxJMRowoA9q7KpaRK+hIwZaLE5jNrrg0pcTaoZaUmTOPKBfKMvpR/nvcD5xpWC5vGuCLBO/4+2Bw5Z7usybOFZt/iIPVkGxVEYaoU26dKM9kR9EW/JRitckq6k33/c5h2+PvrrIT8zb6aXS9xAL6Ty6WoDJLRqQHc1aoRPaARTNvEPLMmIFe1DxhIGjDze+VA3wZ/TfbOCpgL6TQ9jf2QK5Eio4CGlw/RtiUt0vfKYH17xNFd9CK8E4tpUXtwmgslS1sFvHOnm/VsTfuhvtAgbxWsG9/5YKLNgPUzQRWDv3A0k4Plo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
