travis:
  secure:
    BINSTAR_TOKEN: E24WV+tf7EW7cBJYcrvboerP6kOECLLCjXBBVHEdwASSTluyz6yqoToDeyp5i2Xnvnbk0PKyTA7bSeFAoqvNbbwIAT3YyexhkOjaA9NVNwOU2Z7c3m0sEQPPIK3+99rkmfsLJPxf/TFtXPh7RFvbsR1OA2euROAfcWY9KtqlpfTGCUrZiK0z67LAeG4wsGyoLRiD9ehAlPGP3e0312oXY8C/VbSSMU2f1zLPb16aoMAQhWkcMbfDZKl+mcjZ0n192uz8r+SEaBh2gf+5hZk2w1LYknqROZcHljhArQShFvO2BQgaMHG8PbrN+EjJy4MWyHM1ABCiZDIxjrr4EKSFDcRICJjV/pPhHKBNn34JWJVFN72LKGSeCOVraoeU9A+dTwjCS8r9Gz/Bh4hYnb4C1qfmGO7THjPLxm0V7ZC6PWThDwILmlwLuV+f5kDXC9ok6Mr03f43QTa2jKE8vIwY0XHuJyYBGZO/wgTjWBdmKRUkYWnUymyRJg3w4glBOeXu5O3WSh9TFN8j7S/ayJ6uvAwdPUoDdAb88dt9xGda0Ra/PtC4tR4wW4E7hJCFr1wdPHuA07OdWJ8k6Ybe38xH7dc64/aIGxAEPhKzSjOUO+uDyqNcNZ186n/W05uL/P2P5gV3NoQfgLFXDJE0uazcUdGZZzJlWWz3Y1cuN26l27Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
